"""
Spartanburg Civic Feed Fetcher
Runs on GitHub Actions weekly, writes results to data/ for Claude to read.

Working sources:
  - WSPA 7News (RSS)
  - Upstate Business Journal (RSS)
  - City of Spartanburg news/agendas (RSS, government site)
  - Urban Planet Spartanburg (HTML scrape with cookie)

Manual sources (blocked from GitHub Actions IPs):
  - Facebook pages (blanket block)
  - Walking Spartan/Substack (blocks bots)
  - Post & Courier (aggressive rate limiting)
  - GoUpstate/Herald-Journal (Gannett paywall)
"""

import os
import json
import time
import datetime
import requests
import feedparser
from bs4 import BeautifulSoup

OUTPUT_DIR = "data"
os.makedirs(OUTPUT_DIR, exist_ok=True)

NOW = datetime.datetime.now(datetime.UTC).isoformat()
CUTOFF_DAYS = 35

HEADERS = {
    "User-Agent": (
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
        "AppleWebKit/537.36 (KHTML, like Gecko) "
        "Chrome/124.0.0.0 Safari/537.36"
    ),
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
    "Accept-Language": "en-US,en;q=0.5",
}


def days_ago(dt):
    if isinstance(dt, datetime.datetime):
        if dt.tzinfo:
            dt = dt.replace(tzinfo=None)
        return (datetime.datetime.utcnow() - dt).days
    return 999


# ── URBAN PLANET ─────────────────────────────────────────────────────────────

# Authenticated RSS feed — "Content I Follow" for member 36749
# Key is a personal token generated by Invision Board, no expiry
URBANPLANET_RSS = (
    "https://forum.urbanplanet.org/discover/3.xml/"
    "?member=36749&key=18d4d12fb124aa5ff6396305eb66dbd7"
)

def fetch_urbanplanet():
    print("Fetching: Urban Planet Spartanburg (authenticated RSS)")
    return parse_feed(URBANPLANET_RSS, "Urban Planet Spartanburg")


# ── RSS FEEDS ────────────────────────────────────────────────────────────────

RSS_FEEDS = [
    # rss.app feeds (Facebook pages + Instagram accounts)
    ("https://rss.app/feeds/raJfXrAx42I8i8eS.xml",  "Spartanburg Eats (Facebook)"),
    ("https://rss.app/feeds/SFJkaypiEf4ERwhS.xml",   "Downtown Spartanburg SC (Facebook)"),
    ("https://rss.app/feeds/xjllCTaAkrwzeRhn.xml",   "City of Spartanburg (Facebook)"),
    ("https://rss.app/feeds/HFtAbfia2rPYEQio.xml",   "McMillan Pazdan Smith (Facebook)"),
    ("https://rss.app/feeds/dTB5ds4ICOCACCwj.xml",   "OneSpartanburg, Inc. (Facebook)"),
    ("https://rss.app/feeds/9LvxocD02Yp8KSDH.xml",   "Johnston Design Group (Facebook)"),
    ("https://rss.app/feeds/Q3es47cv2kKbmTvN.xml",   "SeamonWhiteside (Instagram)"),
    ("https://rss.app/feeds/O04e2vkehBq6O3w4.xml",   "Strong Towns Spartanburg (Instagram)"),
    # Direct RSS feeds
    ("https://www.wspa.com/feed/",                    "WSPA 7News"),
    ("https://upstatebusinessjournal.com/feed/",      "Upstate Business Journal"),
    ("https://www.cityofspartanburg.org/RSSFeed.aspx?ModID=64&CID=All-0",
     "City of Spartanburg News"),
    ("https://www.cityofspartanburg.org/RSSFeed.aspx?ModID=54&CID=All-0",
     "City of Spartanburg Agendas"),
]

def parse_feed(url, source_name, retries=2):
    print(f"Fetching RSS: {source_name}")
    for attempt in range(retries):
        try:
            resp = requests.get(url, headers=HEADERS, timeout=20)
            resp.raise_for_status()
            feed = feedparser.parse(resp.content)
            items = []
            for entry in feed.entries:
                pub = None
                for field in ("published", "updated", "created"):
                    val = getattr(entry, field, None)
                    if val:
                        try:
                            import email.utils
                            pub = email.utils.parsedate_to_datetime(val).replace(tzinfo=None)
                            break
                        except Exception:
                            pass
                if pub and days_ago(pub) > CUTOFF_DAYS:
                    continue
                desc = ""
                if hasattr(entry, "summary"):
                    desc = BeautifulSoup(entry.summary, "lxml").get_text(" ", strip=True)[:500]
                items.append({
                    "title": getattr(entry, "title", ""),
                    "link": getattr(entry, "link", ""),
                    "published": pub.isoformat() if pub else None,
                    "description": desc,
                    "source": source_name,
                })
            print(f"  → {len(items)} items")
            return items
        except Exception as e:
            print(f"  attempt {attempt+1} failed: {e}")
            if attempt < retries - 1:
                time.sleep(10)
    print(f"  → 0 items after {retries} attempts")
    return []


# ── MAIN ─────────────────────────────────────────────────────────────────────

def main():
    all_items = []

    # Urban Planet subforum
    all_items.extend(fetch_urbanplanet())

    # RSS feeds
    for url, name in RSS_FEEDS:
        all_items.extend(parse_feed(url, name))

    # Sort newest first
    all_items.sort(key=lambda x: x.get("published") or "", reverse=True)

    output = {
        "generated": NOW,
        "item_count": len(all_items),
        "cutoff_days": CUTOFF_DAYS,
        "items": all_items,
    }
    with open(f"{OUTPUT_DIR}/feeds.json", "w") as f:
        json.dump(output, f, indent=2)

    lines = [f"Spartanburg Civic Feeds — {NOW}", "=" * 60, ""]
    for item in all_items:
        lines.append(f"[{item['source']}] {item['published'] or 'n/d'}")
        lines.append(f"  {item['title']}")
        if item["description"] and item["description"] != item["title"]:
            lines.append(f"  {item['description'][:200]}")
        lines.append(f"  {item['link']}")
        lines.append("")

    with open(f"{OUTPUT_DIR}/feeds.txt", "w") as f:
        f.write("\n".join(lines))

    print(f"\nDone — {len(all_items)} total items written to {OUTPUT_DIR}/")
    print("\nNOTE: Facebook pages, Walking Spartan, Post & Courier, GoUpstate")
    print("are blocked from GitHub Actions IPs — check these manually.")


if __name__ == "__main__":
    main()
